server:
  port: 4060

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: system
    password: nm_system_101
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL1
  elasticjob:
    zookeeper:
      server-lists: 127.0.0.1:2181
      namespace: irms-daemon
