server:
  port: 4050

spring:
  rabbitmq:
    host: 139.224.200.249
    port: 5682
    username: pig
    password: lengleng

sms:
  aliyun:
    accessKey: accessKey
    secretKey: secretKey
    channels:
      loginCodeChannel: SMS_34630023
